# Generated by Django 5.0.3 on 2024-04-04 06:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Url",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=6, unique=True)),
                ("url", models.URLField(max_length=2000)),
                ("short_url", models.URLField(blank=True, max_length=2000)),
            ],
        ),
    ]
